import '@/lib/theme/css/style.css'
import { FontInter } from '@/lib/theme'
import { ClerkProvider, RadixProvider } from '@/lib/provider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body>
            <ClerkProvider>
               <RadixProvider appearance='dark' className={FontInter.className}>
                  {children}
               </RadixProvider>
            </ClerkProvider>
         </body>
      </html>
   )
}
