import { Provider, Ui } from '@/components'
import '@/components/theme/css/style.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
   title: 'WheelWise CRM',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body suppressHydrationWarning>
            <Provider.Clerk>
               <Provider.Radix appearance='dark'>
                  <Ui.Font name='Inter'>{children}</Ui.Font>
               </Provider.Radix>
            </Provider.Clerk>
         </body>
      </html>
   )
}
