import type { Metadata } from 'next'

import '@/lib/css/globals.css'
import { ThemeProvider } from '@/lib/provider/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <ClerkProvider>
         <html lang='en'>
            <body>
               <ThemeProvider
                  attribute='class'
                  defaultTheme='system'
                  enableSystem
                  disableTransitionOnChange
               >
                  {children}
               </ThemeProvider>
            </body>
         </html>
      </ClerkProvider>
   )
}
