import { ClerkProvider, RadixProvider } from '@/lib/provider'
import '@/lib/style/css/style.css'
import { FontInter } from '@/lib/style/font'
import type { Metadata } from 'next'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body className={FontInter.className}>
            <ClerkProvider>
               <RadixProvider appearance='dark'>{children}</RadixProvider>
            </ClerkProvider>
         </body>
      </html>
   )
}
