import { ClerkProvider, RadixProvider } from '@/lib/provider'
import { FontInter } from '@/lib/style/font'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body className={FontInter.className}>
            <ClerkProvider>
               <RadixProvider appearance='dark'>{children}</RadixProvider>
            </ClerkProvider>
         </body>
      </html>
   )
}
